### ISSUE TITLE
Exit unexpectedly at training

### ISSUE THREAD

**Issue by tijiang13** [tticoin/LSTM-ER#4]
When running this code after compiling, the program gets killed at the first iteration of training.

```
build/relation/RelationExtraction --train -y yaml/parameter-semeval-2010.yaml

306560 words, 200 dimensions
start loading documents in data/semeval-2010/corpus/train/
start loading documents in data/semeval-2010/corpus/test/
==== iteration: 1 =====
train: 
killed
```

After adding some `print`, I find it breaks when conducting the function

```
# LSTM-ER/relation/RelLSTMModel 
# void RelLSTMModel::predict(vector<Table*> &tables, bool do_update, bool output, bool ent_only)
sgd_->update(params_.gradient_scale()/params_.minibatch()); # the 306 line
```

and the output of `build/relation/RelationExtraction --train -y yaml/parameter-semeval-2010.yaml` shows that this program treat every case as **negative**, which is obvious wrong.

Do you have any idea? Or have you tested your code in a brand new (virtual) machine with Ubuntu?

**Comment by mmiwa** [comment]
The model is not trained correctly, and maybe the error is due to the memory limit (process is killed by the OS).

As in README.md, we have developed the system with Fedora. We once succeeded to run it on Ubuntu and we have got several working reports, so this program should work on Ubuntu.

**Comment by tijiang13** [comment]
Thanks, I originally run this code in a virtual machine, and it seems that the memory allocated by default is merely 4GB, which turns out to be far from enough.

**Comment by tijiang13** [comment]
CLOSED.
